services:
  mongodb:
    image: docker.io/library/mongo:7
    container_name: mongodb
    networks:
      - mongo-net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: docker.io/library/mongo-express:latest
    container_name: mongo-express
    networks:
      - mongo-net
    ports:
      - "8081:8081"
    environment:
      # Credenciais para entrar na página web do Mongo Express
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      # A URL de conexão corrigida apontando para o serviço 'mongodb' e banco 'admin'
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017/admin?authSource=admin
    depends_on:
      - mongodb

networks:
  mongo-net:
    driver: bridge

volumes:
  mongo_data: